name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # Allows manual execution from Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # If using Large File Storage

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"

      - name: Authenticate & Push to Hugging Face
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/deepseek
          git push origin main
